// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUru_fYDOyRcRb1IA4iVQKrbbEZJnpEh8',
    appId: '1:346385082468:web:7df6427d263e65297d1771',
    messagingSenderId: '346385082468',
    projectId: 'smartwaste-387b1',
    authDomain: 'smartwaste-387b1.firebaseapp.com',
    storageBucket: 'smartwaste-387b1.firebasestorage.app',
    measurementId: 'G-EGYLZEN019',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN4tDU-GJwHayxEofc6gvvhr0EedTMsjs',
    appId: '1:346385082468:android:468b4bf319065fca7d1771',
    messagingSenderId: '346385082468',
    projectId: 'smartwaste-387b1',
    storageBucket: 'smartwaste-387b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzT85SF1A3v-bHCeHTM0zp9sK5nMgC1bI',
    appId: '1:346385082468:ios:23d0f589ea062fdd7d1771',
    messagingSenderId: '346385082468',
    projectId: 'smartwaste-387b1',
    storageBucket: 'smartwaste-387b1.firebasestorage.app',
    iosBundleId: 'com.example.smartWaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzT85SF1A3v-bHCeHTM0zp9sK5nMgC1bI',
    appId: '1:346385082468:ios:23d0f589ea062fdd7d1771',
    messagingSenderId: '346385082468',
    projectId: 'smartwaste-387b1',
    storageBucket: 'smartwaste-387b1.firebasestorage.app',
    iosBundleId: 'com.example.smartWaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUru_fYDOyRcRb1IA4iVQKrbbEZJnpEh8',
    appId: '1:346385082468:web:6a368485ce8de39f7d1771',
    messagingSenderId: '346385082468',
    projectId: 'smartwaste-387b1',
    authDomain: 'smartwaste-387b1.firebaseapp.com',
    storageBucket: 'smartwaste-387b1.firebasestorage.app',
    measurementId: 'G-0W1XZ4QYFX',
  );
}
